AWSTemplateFormatVersion : "2010-09-09"
Description: "CloudFormation Template for deploying S3 Bucket"

Parameters:
  project:
    Type: String
    Description:  Project Name
  app:
    Type: String
    Description:  Application Name   
  env:
    Type: String
    AllowedValues: [prod, dev, qa, stag]
    Description:  Environment Name
  bucketName:
    Type: String
    Description: Bucket Name
  versioningStatus:
    Type: String
    Description: Status of Versioning
    AllowedValues: [Enabled, Suspended]
  indexDocument:
    Type: String
    Description: The name of the index document for the website
  errorDocument:
    Type: String
    Description: The name of the error document for the website

Resources:
  s3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${project}-${app}-${env}-${bucketName}-${AWS::Region}-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: !Ref indexDocument
        ErrorDocument: !Ref errorDocument
      VersioningConfiguration:
        Status: !Ref versioningStatus
      Tags:
        - Key: name
          Value: !Sub "${project}-${app}-${env}-s3Bucket"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: env
          Value: !Ref env

Outputs:
  s3BucketName:
    Value: !Ref s3Bucket
    Export:
      Name: !Sub "${project}-${app}-${env}-s3Bucket-${AWS::Region}"